### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tasuwo** [tasuwo/BlogByCakePHP#5]
気づいたことを書いておく
- [ ] トラックバックの機能をつける
- [ ] タグの編集/削除．簡単に実装できるけど，UIをどうするか
- [ ] プロフィールを設定して，サイドバーに表示できる
- [x] 記事の paginate
- [ ] 記事の本文を Markdown に対応させる
- [ ] 記事に more ボタンを付加できるようにする
- [ ] コメント投稿者が自分のコメントの編集/削除を行えるようにする？
- [ ] ブログの設定画面とか作る？ブログのタイトルとか設定できたりとか...
- [ ] サイドバーにタグ一覧
- [ ] サイドバーに recent posts
- [ ] 投稿完了した時にメッセージ出さないと不安かもしれない

``` diff
- foo
+ bar
```
